### ISSUE TITLE
CLI not working for me, "no such folder"

### ISSUE THREAD

**Issue by ivansabik** [PierreRambaud/groove-dl#7]
Another report here, I cannot get the CLI version to work, GUI is working however. Seems to be complaining about a folder that doesn't exist.
Already chmoed the folder for permissions, also tried with -o ./ but didn't work either, here's my output:

```
tabarnak@tabarnak:~$ groove-dl-cli -p 64902044
/var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:127:in `initialize': No such file or directory - /tmp/Roger Sanchez/Another Chance/Another Chance (Afterlife mix).mp3 (Errno::ENOENT)
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:127:in `open'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:127:in `block in process_cli_response'
    from /usr/lib/ruby/1.9.1/net/http.rb:1323:in `block (2 levels) in transport_request'
    from /usr/lib/ruby/1.9.1/net/http.rb:2672:in `reading_body'
    from /usr/lib/ruby/1.9.1/net/http.rb:1322:in `block in transport_request'
    from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
    from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
    from /usr/lib/ruby/1.9.1/net/http.rb:1294:in `request'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:270:in `net_http_do_request'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:416:in `block in transmit'
    from /usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    from /var/lib/gems/1.9.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:73:in `download'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:86:in `block in download_queue'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:85:in `each'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:85:in `download_queue'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/downloader.rb:53:in `playlist'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/lib/groove-dl/cli.rb:43:in `block (2 levels) in default_options'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:260:in `call'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
    from /var/lib/gems/1.9.1/gems/groove-dl-0.3.1/bin/groove-dl-cli:15:in `<top (required)>'
    from /usr/local/bin/groove-dl-cli:23:in `load'
    from /usr/local/bin/groove-dl-cli:23:in `<main>'
```

**Comment by PierreRambaud** [comment]
Should be fixed with the version 0.4.0, more, I remove the executable groove-dl-cli, there is only one now as it says in the README.
Thanks again for your feedback, you have revealed other bugs by showing me this one ;)
